### ISSUE TITLE
Method error : Invalid pattern (.Parse())

### ISSUE THREAD

**Issue by RemiLou** [AgileFlexAgency/MatomoDeviceDetector.NET#1]
I've got a bug when i used this method : 
`var browsers = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"`
`var result = new DeviceDetector(browsers);`
 `result.Parse();`

It crashes on .Parse() method
This problem come from 4.7.9 version to the latest

Error : Invalid pattern '(?:^|[^A-Z0-9\-_]|[^A-Z0-9\-]_|sprd-)(?:JIAYU[ _-]|(?:JY-G4[\_]G5|(?:JY-[a-z0-9]+)|JY_G4C)(?:[);\/ ]|$))' at offset 62. Unrecognized escape sequence \\_.

**Comment by AgileFlexAgency** [comment]
Hello @RemiLou - You can create a PR and we can revert to the 4.7.9 pattern :)

**Comment by xavierlaffargue** [comment]
Hi, @AgileFlexAgency can you fix this issue?

**Comment by AgileFlexAgency** [comment]
Hello @xavierlaffargue,

Feel free to create a PR in order to revert to the 4.7.9 pattern.

Thank you :)

**Comment by xavierlaffargue** [comment]
I create a PR #2

**Comment by xavierlaffargue** [comment]
When a new NuGet package  will be available ?

**Comment by AgileFlexAgency** [comment]
Hello @xavierlaffargue @RemiLou 

You can update the Nuget Package to the latest 4.8.3 released version: https://www.nuget.org/packages/MatomoDeviceDetector.NET/4.8.3

Thank you.
