### ISSUE TITLE
DeviceParserAbstract class throwing exception on construction due to duplicate keys in the DeviceBrands dictionary

### ISSUE THREAD

**Issue by LiamJGarrett** [AgileFlexAgency/MatomoDeviceDetector.NET#2]
Pull request to fix the issue: 
https://github.com/AgileFlexAgency/MatomoDeviceDetector.NET/pull/1

**Comment by AgileFlexAgency** [comment]
Thank you @LiamJGarrett for finding the issue.

**Comment by AgileFlexAgency** [comment]
Fixed with the 28-January-2020 release.
