### ISSUE TITLE
Licence Coyright

### ISSUE THREAD

**Issue by totpero** [AgileFlexAgency/MatomoDeviceDetector.NET#3]
Hi,
Please specify this code is all cloned from https://github.com/totpero/DeviceDetector.NET and you don't specified this.
You can fork from original and you can create pull requests. From this is based open sources not for copy/paste and rename projects.

https://github.com/totpero/DeviceDetector.NET/blob/master/LICENSE
Please specify the original project.

**Comment by Findus23** [comment]
Comparing the code it seems quite obvious that this is mostly a copy of https://github.com/totpero/DeviceDetector.NET with all occurrences of DeviceDetectorNET replaced with MatomoDeviceDetectorNET. This is also okay, as the Apache License allows to create deriverative works: 

>    4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:
> https://github.com/totpero/DeviceDetector.NET/blob/f54c9f700656a20afbc88850f809175be01a8ec6/LICENSE#L89-L92

But this means you also need to follow the conditions that follow below:


>  (a) You must give any other recipients of the Work or Derivative Works a copy of this License; and

This repo does not contain a copy of the original license file, but just a modified license called `Version 4.6.9` (which does not exist).
https://github.com/AgileFlexAgency/MatomoDeviceDetector.NET/blob/d17f15a967a3f3afe44b0d878811e5c0bb48f673/LICENSE#L1-L3

> (b) You must cause any modified files to carry prominent notices stating that You changed the files; and

Nowhere in this repository or in the modified lines one can find a notice that this is a deriverative work of the original software project. 

> (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

The original software contains a very obvious copyright notice:
>   ```XML
> <Copyright>Copyright © www.totpe.ro</Copyright>
> ```
> https://github.com/totpero/DeviceDetector.NET/blob/f54c9f700656a20afbc88850f809175be01a8ec6/DeviceDetector.NET/DeviceDetector.NET.csproj#L9

Not only was this notice removed, violating the original license, it was also replaced with a new invalid copyright notice:
https://github.com/AgileFlexAgency/MatomoDeviceDetector.NET/blob/d17f15a967a3f3afe44b0d878811e5c0bb48f673/MatomoDeviceDetector.NET/MatomoDeviceDetector.NET.csproj#L8


This means that the software in this repository seems to be in violation of three of the conditions of the license and I would therefore ask you @AgileFlexAgency to fix this as soon as possible.

**Comment by totpero** [comment]
Mai ales ca si voi sunteti din Romania, va rog nu mai promovati astfel de practici... Daca stiti ce inseamna sa programezi si sa fi mandru de ce cod scrii.... daca promovam munca furata de la altii nu este ok. Faceti un fork de la proiectul meu si puteti continua sa contribuiti la fel cum au facut si altii si cum se si face. Nu ma asteptam sa fiti chiar romani.... Pacat daca ati incerca in cotinuare sa va laudati cu munca altuia.... asta ar da dovada de o calitate a produselor.... si ma gandesc ca nu este astfel.

**Comment by AgileFlexAgency** [comment]
@totpero @Findus23 We can adjust the copyright per your request no worries about it. Just let us know what to change. Feel free to comment here, make a PR or contact us at agile@agile-flex.com
